/**
 * Generated by tsnapi — public API snapshot of `mdquiz` */
// Interfaces
export interface AnswerOption {
  id: string;
  text: string;
  isCorrect: boolean;
  explanation?: string;
}
export interface ParseDirOptions {
  recursive?: boolean;
  filePrefix?: string;
}
export interface Question {
  id: string;
  question: string;
  answers: AnswerOption[];
  isMultiSelect: boolean;
  hint?: string;
  codeBlock?: string;
  frontmatter: Record<string, unknown>;
}

// Functions
export declare function parseDirectory(_: string, _?: ParseDirOptions): Question[];
export declare function parseQuestionFile(_: string, _: string): Question;